window.presentationsData = [
  {
    "year": "2025",
    "date": "2025/12/8-12",
    "titleEn": "Thermal Structure of Magnetized Protoplanetary Disks and Its Implications for Planet Formation",
    "titleJa": "Thermal Structure of Magnetized Protoplanetary Disks and Its Implications for Planet Formation",
    "authorsEn": "S. Mori",
    "authorsJa": "森 昇志",
    "confEn": "International Conference on Exoplanets and Planet Formation",
    "confJa": "International Conference on Exoplanets and Planet Formation",
    "type": "poster",
    "scope": "international",
    "placeEn": "Sheraton Grand Shanghai Pudong Hotel, Shanghai, China",
    "placeJa": "上海 (中国)",
    "url": "https://indico-tdli.sjtu.edu.cn/event/4089/",
    "posterUrl": "files/posters/poster-20251208-epf-thermal-structure-magnetized-ppds.pdf"
  },
  {
    "year": "2025",
    "date": "2025/10",
    "titleEn": "Ionization, Radiation, and MHD in Protoplanetary Disks",
    "titleJa": "Ionization, Radiation, and MHD in Protoplanetary Disks",
    "authorsEn": "S. Mori",
    "authorsJa": "森 昇志",
    "confEn": "Extra Dimensions in Planet Formation",
    "confJa": "Extra Dimensions in Planet Formation",
    "type": "oral",
    "scope": "international",
    "placeEn": "Sky Hill Hotel Izu Kogen, Ito, Japan",
    "placeJa": "スカイヒルホテル伊豆高原 (伊東市, 静岡県)",
    "url": null
  },
  {
    "year": "2025",
    "date": "2025/09/09-11",
    "titleEn": "Global Nonideal MHD Simulations of Protoplanetary Disks: Episodic Surface Accretion",
    "titleJa": "原始惑星系円盤の大局的非理想磁気流体力学シミュレーション：間欠的な表層降着",
    "authorsEn": "S. Mori, X. Bai, K. Tomida",
    "authorsJa": "森 昇志, Xuening Bai, 富田賢吾",
    "confEn": "The Astronomical Society of Japan Autumn Meeting 2025",
    "confJa": "日本天文学会2025年秋季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Kaikyo Messe Shimonoseki, Shimonoseki, Japan",
    "placeJa": "海峡メッセ下関 (下関市, 山口県)",
    "url": "https://www.asj.or.jp/nenkai/archive/2025b/book.pdf",
    "slideUrl": "files/slides/slide-20250911-asj-autumn-global-nonideal-mhd.pdf"
  },
  {
    "year": "2025",
    "date": "2025/8/24-29",
    "titleEn": "Temperature Structure and Its Evolution of Magnetized Protoplanetary Disks",
    "titleJa": "Temperature Structure and Its Evolution of Magnetized Protoplanetary Disks",
    "authorsEn": "S. Mori",
    "authorsJa": "森 昇志",
    "confEn": "Exoplanets & Planet Formation Workshop 2025",
    "confJa": "Exoplanets & Planet Formation Workshop 2025",
    "type": "oral",
    "scope": "international",
    "placeEn": "Yunnan Dianchi Garden Resort Hotel & Spa, Kunming, China",
    "placeJa": "昆明 (雲南省, 中国)",
    "url": "https://epf2025.github.io"
  },
  {
    "year": "2025",
    "date": "2025/1/28",
    "titleEn": "Magnetic Circumplanetary Disks",
    "titleJa": "Magnetic Circumplanetary Disks",
    "authorsEn": "S. Mori",
    "authorsJa": "森 昇志",
    "confEn": "Circumplanetary Disks and Satellite Formation III",
    "confJa": "Circumplanetary Disks and Satellite Formation III",
    "type": "oral",
    "scope": "international",
    "placeEn": "Science Seminar House, Kyoto University, Kyoto, Japan",
    "placeJa": "京都大学理学研究科セミナーハウス (京都市, 京都府)",
    "url": "https://sites.google.com/view/cpdsf2025/home",
    "slideUrl": "files/slides/slide-20250128-cpdsf3-magnetic-circumplanetary-disks.pdf"
  },
  {
    "year": "2024",
    "date": "2024/9/24-26",
    "titleEn": "Long-term Thermal Evolution of Magnetized Protoplanetary Disks with Mass Loss: Impact on Super-Earth Formation",
    "titleJa": "質量損失を伴う磁気的な原始惑星系円盤の長期温度進化：スーパーアース形成に与える影響",
    "authorsEn": "S. Mori, M. Kunitomo, M. Ogihara",
    "authorsJa": "森 昇志, 國友 正信, 荻原 正博",
    "confEn": "The Japanese Society for Planetary Sciences Autumn Meeting 2024",
    "confJa": "日本惑星科学会 2024年 秋季講演会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Kyushu University Medical Centennial Hall, Fukuoka, Japan",
    "placeJa": "九州大学医学部百年講堂 (福岡市, 福岡県)",
    "url": "https://www.wakusei.jp/meetings/fallmeeting/2024/index.html"
  },
  {
    "year": "2024",
    "date": "2024/3/18-22",
    "titleEn": "Magnetized Protoplanetary Disks",
    "titleJa": "Magnetized Protoplanetary Disks",
    "authorsEn": "S. Mori",
    "authorsJa": "森 昇志",
    "confEn": "SPiCE: Simulating Physics in Celestial Ecosystems",
    "confJa": "SPiCE: Simulating Physics in Celestial Ecosystems",
    "type": "invited",
    "scope": "international",
    "placeEn": "Aoba Science Hall, Science Complex C, Tohoku University, Sendai, Japan",
    "placeJa": "東北大学 理学研究科合同C棟 青葉サイエンスホール (仙台市, 宮城県)",
    "url": "https://www.astr.tohoku.ac.jp/~tomida/spice/"
  },
  {
    "year": "2023",
    "date": "2023/12/16-19",
    "titleEn": "Temperature Structure of Magnetized Protoplanetary Disks",
    "titleJa": "Temperature Structure of Magnetized Protoplanetary Disks",
    "authorsEn": "S. Mori",
    "authorsJa": "森 昇志",
    "confEn": "Exoplanets & Planet Formation Workshop 2023",
    "confJa": "Exoplanets & Planet Formation Workshop 2023",
    "type": "poster",
    "scope": "international",
    "placeEn": "Beijing, China",
    "placeJa": "北京 (中国)",
    "url": "https://epf2023.casconf.cn/",
    "posterUrl": "files/posters/poster-20231216-epf-temperature-structure-magnetized-ppds.pdf"
  },
  {
    "year": "2023",
    "date": "2023/10/01-05",
    "titleEn": "Radiative Nonideal MHD Simulations of Inner Protoplanetary Disks",
    "titleJa": "Radiative Nonideal MHD Simulations of Inner Protoplanetary Disks",
    "authorsEn": "S. Mori, X. Bai, K. Tomida",
    "authorsJa": "森 昇志, Xuening Bai, 富田賢吾",
    "confEn": "Magnetohydrodynamical Flows in Young Circumstellar Disks",
    "confJa": "Magnetohydrodynamical Flows in Young Circumstellar Disks",
    "type": "invited",
    "placeEn": "Schloss Ringberg, Kreuth, Germany",
    "placeJa": "リングベルク城 (クロイト, ドイツ)",
    "url": "https://www.ufos-project.eu/mhd-2023"
  },
  {
    "year": "2023",
    "date": "2023/09/20-22",
    "titleEn": "Thermal Structure of Inner Magnetized Disks: Radiative Nonideal MHD Simulations",
    "titleJa": "原始惑星系円盤内側の熱構造: 輻射輸送入り大局的非理想磁気流体力学シミュレーション",
    "authorsEn": "S. Mori, X. Bai, K. Tomida",
    "authorsJa": "森 昇志, Xuening Bai, 富田賢吾",
    "confEn": "The Astronomical Society of Japan Autumn Meeting 2023",
    "confJa": "日本天文学会2023年秋季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Nagoya University, Nagoya, Japan",
    "placeJa": "名古屋大学 (名古屋市, 愛知県)",
    "url": "https://www.asj.or.jp/nenkai/archive/2023b/book.pdf"
  },
  {
    "year": "2023",
    "date": "2023/5/7-13",
    "titleEn": "Nonideal MHD Simulations to Understand the Temperature Structure of Protoplanetary Disks",
    "titleJa": "Nonideal MHD Simulations to Understand the Temperature Structure of Protoplanetary Disks",
    "authorsEn": "S. Mori, X. Bai, K. Tomida",
    "authorsJa": "森 昇志, Xuening Bai, 富田賢吾",
    "confEn": "SPIDI: The Inner Disk of Young Stars: Accretion, Ejection, and Planet Formation",
    "confJa": "SPIDI: The Inner Disk of Young Stars: Accretion, Ejection, and Planet Formation",
    "type": "poster",
    "placeEn": "Cargèse, France",
    "placeJa": "カルジェズ (フランス)",
    "url": "https://spidi23.insight-outside.fr/"
  },
  {
    "year": "2023",
    "date": "2023/04/10-15",
    "titleEn": "Radiative Nonideal MHD Simulations of the Inner Protoplanetary Disks",
    "titleJa": "Radiative Nonideal MHD Simulations of the Inner Protoplanetary Disks",
    "authorsEn": "S. Mori, X. Bai, K. Tomida",
    "authorsJa": "森 昇志, Xuening Bai, 富田賢吾",
    "confEn": "Protostars and Planets VII",
    "confJa": "Protostars and Planets VII",
    "type": "poster",
    "placeEn": "Kyoto International Conference Center, Kyoto, Japan",
    "placeJa": "国立京都国際会館 (京都市, 京都府)",
    "url": "https://ppvii.org/"
  },
  {
    "year": "2023",
    "date": "2023/1/26",
    "titleEn": "Numerical Simulations of Protoplanetary Disks to Elucidate Planet Formation Processes: Current Status and Future Prospects",
    "titleJa": "惑星形成過程の解明に向けた原始惑星系円盤の数値シミュレーション：現状と展望",
    "authorsEn": "S. Mori",
    "authorsJa": "森 昇志",
    "confEn": "CfCA Users Meeting 2022",
    "confJa": "CfCA Users Meeting 2022",
    "type": "invited",
    "scope": "domestic",
    "placeEn": "NAOJ Mitaka Campus, Mitaka, Japan",
    "placeJa": "国立天文台 三鷹キャンパス (三鷹市, 東京都)",
    "url": "https://www.cfca.nao.ac.jp/um2022_program"
  },
  {
    "year": "2022",
    "date": "2022/09/15",
    "titleEn": "Temperature Structure from Global Nonideal MHD Simulations of Protoplanetary Disks",
    "titleJa": "大局的非理想磁気流体シミュレーションから明らかにする原始惑星系円盤の温度構造",
    "authorsEn": "S. Mori, X. Bai, K. Tomida",
    "authorsJa": "森 昇志, Xuening Bai, 富田賢吾",
    "confEn": "The Astronomical Society of Japan Autumn Meeting 2022",
    "confJa": "日本天文学会2022年秋季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Niigata University, Niigata, Japan",
    "placeJa": "新潟大学 (新潟市, 新潟県)",
    "url": "https://www.asj.or.jp/nenkai/archive/2022b/book.pdf"
  },
  {
    "year": "2022",
    "date": "2022/09/20",
    "titleEn": "Temperature Structure of Magnetized Protoplanetary Disks from Global Nonideal MHD Simulations",
    "titleJa": "大局的非理想磁気流体シミュレーションから探る原始惑星系円盤の温度構造",
    "authorsEn": "S. Mori, K. Tomida, X. Bai",
    "authorsJa": "森 昇志, 富田賢吾, Xuening Bai",
    "confEn": "The Japanese Society for Planetary Science 2022 Fall Meeting",
    "confJa": "日本惑星科学会 2022年 秋季講演会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "The Hirosawa City Hall, Mito, Ibaraki, Japan",
    "placeJa": "ザ・ヒロサワ・シティ会館 (水戸市, 茨城県)",
    "url": "https://www.wakusei.jp/meetings/fallmeeting/2022/index.html"
  },
  {
    "year": "2022",
    "date": "2022/3/23-25",
    "titleEn": "Temperature Structure from Global Nonideal MHD Simulations of Protoplanetary Disks",
    "titleJa": "大局的非理想磁気流体シミュレーションから明らかにする原始惑星系円盤の温度構造",
    "authorsEn": "S. Mori",
    "authorsJa": "森 昇志, Xuening Bai, 富田賢吾",
    "confEn": "Planet Formation Debate 2022 Spring",
    "confJa": "惑星形成討論会2022春",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Tohoku University, Sendai, Japan",
    "placeJa": "東北大学 (仙台市, 宮城県)",
    "url": null
  },
  {
    "year": "2021",
    "date": "2021/09/09",
    "titleEn": "Modeling Magnetic Circumplanetary Disks: Wind-driven Accretion Regions",
    "titleJa": "磁場が降着を駆動する周惑星円盤のモデル化: 円盤風駆動降着領域",
    "authorsEn": "S. Mori, Y. Shibaike",
    "authorsJa": "森 昇志, 芝池 諭人",
    "confEn": "The Astronomical Society of Japan Autumn Meeting 2021",
    "confJa": "日本天文学会2021年秋季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Online",
    "placeJa": "オンライン",
    "url": "https://www.asj.or.jp/nenkai/archive/2021b/book.pdf"
  },
  {
    "year": "2021",
    "date": "2021/03/04",
    "titleEn": "Mock Observations of Rotating Infalling Envelopes: Re-analysis of L1527 Observations",
    "titleJa": "回転降着エンべロープの模擬観測: L1527観測の再解析",
    "authorsEn": "S. Mori, Y. Aikawa, Y. Oya, S. Yamamoto, N. Sakai",
    "authorsJa": "森 昇志, 相川 祐理, 大屋瑤子, 山本聡, 坂井南美",
    "confEn": "The Astronomical Society of Japan 2021 Spring Meeting",
    "confJa": "日本天文学会2021年春季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Online",
    "placeJa": "オンライン",
    "url": "https://www.asj.or.jp/nenkai/archive/2021a/book.pdf"
  },
  {
    "year": "2020",
    "date": "2020/11/12",
    "titleEn": "Magnetic Accretion and Snowline Migration in Protoplanetary Disks",
    "titleJa": "磁気的に降着する原始惑星系円盤におけるスノーラインの移動:地球型惑星の形成過程への示唆",
    "authorsEn": "S. Mori, S. Okuzumi, M. Kunitomo, X. Bai",
    "authorsJa": "森 昇志, 奥住 聡, 國友 正信, Xuening Bai",
    "confEn": "The Japanese Society for Planetary Sciences Autumn Meeting 2020",
    "confJa": "日本惑星科学会 2020年 秋季講演会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Online",
    "placeJa": "オンライン",
    "url": "https://www.wakusei.jp/meetings/fallmeeting/2020/index.html"
  },
  {
    "year": "2020",
    "date": "2020/09/09",
    "titleEn": "Mock Observations of Rotating Infalling Envelopes Based on Hydrodynamics: Estimating Central Stellar Mass",
    "titleJa": "流体力学に基づいた回転降着エンベロープの模擬観測:中心星質量の推定",
    "authorsEn": "S. Mori, Y. Aikawa, R. Oya, S. Yamamoto",
    "authorsJa": "森 昇志, 相川 祐理, 大屋瑤子, 山本智",
    "confEn": "The Astronomical Society of Japan 2020 Autumn Meeting",
    "confJa": "日本天文学会2020年秋季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Online",
    "placeJa": "オンライン",
    "url": "http://www.asj.or.jp/nenkai/archive/2020b/prog.pdf"
  },
  {
    "year": "2020",
    "date": "2020/4/14-17",
    "titleEn": "Evolution of the Water Snowline in Magnetized Protoplanetary Disks",
    "titleJa": "Evolution of the Water Snowline in Magnetized Protoplanetary Disks",
    "authorsEn": "S. Mori, S. Okuzumi, M. Kunitomo, X. Bai",
    "authorsJa": "森 昇志, 奥住 聡, 國友 正信, X. Bai",
    "confEn": "Building Blocks of Planets 2020",
    "confJa": "Building Blocks of Planets 2020",
    "type": "invited",
    "scope": "international",
    "placeEn": "Online",
    "placeJa": "オンライン",
    "url": "https://www.ufos-project.eu/building-blocks-of-planets-2020"
  },
  {
    "year": "2020",
    "date": "2020/3/16-19",
    "titleEn": "SPICA Observation of Water Emission Reveals Thermal and Dynamical Structures of Protoplanetary Disks",
    "titleJa": "SPICAの水輝線観測が明らかにする原始惑星系円盤の熱･力学構造",
    "authorsEn": "S. Mori, SPICA planet formation working group",
    "authorsJa": "森 昇志, SPICAワーキンググループ",
    "confEn": "The Astronomical Society of Japan 2020 Spring Meeting",
    "confJa": "日本天文学会2020年春季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Online",
    "placeJa": "オンライン",
    "url": "http://www.asj.or.jp/nenkai/prog2020a.pdf"
  },
  {
    "year": "2020",
    "date": "2020/9/30-10/3",
    "titleEn": "Evolution of the Snowline in Magnetically Accreting Disks: Implications for Terrestrial Planet Formation",
    "titleJa": "磁気降着円盤におけるスノーラインの進化: 地球型惑星の形成過程への示唆",
    "authorsEn": "S. Mori, S. Okuzumi, M. Kunitomo, X. Bai",
    "authorsJa": "森 昇志, 奥住 聡, 國友 正信, Xuening Bai",
    "confEn": "JSPS Grant-in-Aid Star and Planet Formation 2020 Large Meeting",
    "confJa": "新学術領域「星惑星形成」2020年度大研究会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Online",
    "placeJa": "オンライン",
    "url": "http://star-planet.jp/2020/09/24/%e5%a4%a7%e7%a0%94%e7%a9%b6%e4%bc%9a2020%e3%81%ae%e9%96%8b%e5%82%ac/"
  },
  {
    "year": "2019",
    "date": "2019/12/8-10",
    "titleEn": "Physical Interpretation of Line Observations of Envelope and Disk Systems: A Case of L1527",
    "titleJa": "Physical interpretation of line observations of envelope and disk systems: a case of L1527",
    "authorsEn": "S. Mori, Y. Aikawa",
    "authorsJa": "森 昇志, 相川 祐理",
    "confEn": "ALMA workshop 2019: Early Planet Formation in Embedded Disks",
    "confJa": "ALMA workshop 2019: Early Planet Formation in Embedded Disks",
    "type": "oral",
    "scope": "international",
    "placeEn": "The University of Tokyo, Bunkyo, Japan",
    "placeJa": "東京大学 (文京区, 日本)",
    "url": "https://ohashi211.wixsite.com/almaws2019"
  },
  {
    "year": "2019",
    "date": "2019/11/25-28",
    "titleEn": "Evolution of the Water Snowline in Magnetized Protoplanetary Disks",
    "titleJa": "Evolution of the Water Snowline in Magnetized Protoplanetary Disks",
    "authorsEn": "S. Mori, S. Okuzumi, M. Kunitomo, X. Bai",
    "authorsJa": "森 昇志, 奥住 聡, 國友 正信, X. Bai",
    "confEn": "PLANET FORMATION WORKSHOP 2019",
    "confJa": "PLANET FORMATION WORKSHOP 2019",
    "type": "oral",
    "scope": "international",
    "placeEn": "NAOJ, Mitaka, Japan",
    "placeJa": "国立天文台 (三鷹)",
    "url": "https://sci.nao.ac.jp/main/en/news-en/651"
  },
  {
    "year": "2019",
    "date": "2019/8/19-23",
    "titleEn": "Evolution of the Water Snowline in Magnetized Protoplanetary Disks",
    "titleJa": "Evolution of the Water Snowline in Magnetized Protoplanetary Disks",
    "authorsEn": "S. Mori, S. Okuzumi, M. Kunitomo, X. Bai",
    "authorsJa": "森 昇志, 奥住 聡, 國友 正信, X. Bai",
    "confEn": "EXTREME SOLAR SYSTEMS IV",
    "confJa": "EXTREME SOLAR SYSTEMS IV",
    "type": "poster",
    "scope": "international",
    "placeEn": "Harpa Center, Reykjavik, Iceland",
    "placeJa": "Harpa Center (レイキャビク, アイスランド)",
    "url": "https://aas.org/meetings/aastcs7/ExSS4"
  },
  {
    "year": "2019",
    "date": "2019/7/8-12",
    "titleEn": "Inefficient Magnetic Accretion Heating in Protoplanetary Disks",
    "titleJa": "Inefficient Magnetic Accretion Heating in Protoplanetary Disks",
    "authorsEn": "S. Mori, S. Okuzumi, X. Bai",
    "authorsJa": "森 昇志, 奥住 聡, X. Bai",
    "confEn": "Ringberg Workshop: Turbulence and Structure Formation in Protoplanetary Disks 2019",
    "confJa": "Ringberg Workshop: Turbulence and Structure Formation in Protoplanetary Disks 2019",
    "type": "oral",
    "scope": "international",
    "placeEn": "Schloss Ringberg, Kreuth, Germany",
    "placeJa": "リングベルク城 (クロイト, ドイツ)",
    "url": "https://www.mpia.de/events/25693/3996213"
  },
  {
    "year": "2019",
    "date": "2019/6/17-20",
    "titleEn": "Inefficient Magnetic Accretion Heating in Protoplanetary Disks",
    "titleJa": "Inefficient Magnetic Accretion Heating in Protoplanetary Disks",
    "authorsEn": "S. Mori, S. Okuzumi, X. Bai",
    "authorsJa": "森 昇志, 奥住 聡, X. Bai",
    "confEn": "From Stars to Planets II - Connecting our understanding of star and planet formation",
    "confJa": "From Stars to Planets II - Connecting our understanding of star and planet formation",
    "type": "oral",
    "scope": "international",
    "placeEn": "Chalmers University of Technology, Gothenburg, Sweden",
    "url": "http://cosmicorigins.space/fstpii"
  },
  {
    "year": "2019",
    "date": "2019/ 5/26-30",
    "titleEn": "Inefficient Accretion Heating in Protoplanetary Disks: Influence on Evolution of Snow Line",
    "titleJa": "原始惑星系円盤の非効率な降着加熱:スノーラインの進化への影響",
    "authorsEn": "S. Mori, X. Bai, S. Okuzumi",
    "authorsJa": "森 昇志, X. Bai, 奥住 聡",
    "confEn": "Japan Geoscience Union Meeting 2019",
    "confJa": "日本地球惑星科学連合2019年大会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Makuhari Messe, Chiba, Japan",
    "placeJa": "幕張メッセ (千葉)",
    "url": "http://www.jpgu.org/meeting_2019/"
  },
  {
    "year": "2018",
    "date": "2018/ 9/24-28",
    "titleEn": "Inefficient Heating by Wind-driven Accretion in Protoplanetary Disks",
    "titleJa": "Inefficient Heating by Wind-driven Accretion in Protoplanetary Disks",
    "authorsEn": "S. Mori, X. Bai, S. Okuzumi",
    "authorsJa": "森 昇志, X. Bai, 奥住 聡",
    "confEn": "Japanese-German meeting on Exoplanets and Planet Formation 2018",
    "confJa": "Japanese-German meeting on Exoplanets and Planet Formation 2018",
    "type": "oral",
    "scope": "international",
    "placeEn": "Schloss Edesheim, Edesheim, Germany",
    "placeJa": "エーデスハイム城 (ドイツ)",
    "url": "http://www2.mpia-hd.mpg.de/homes/jg2018/#program"
  },
  {
    "year": "2019",
    "date": "2019/9/24-26",
    "titleEn": "Wind-driven Accretion in Circumplanetary Disks",
    "titleJa": "Wind-driven Accretion in Circumplanetary Disks",
    "authorsEn": "S. Mori, Y. Shibaike",
    "authorsJa": "森 昇志, 芝池 諭人",
    "confEn": "Planetary and Satellite System Workshop 2019",
    "confJa": "惑星・衛星系研究会2019",
    "type": "oral",
    "scope": "international",
    "placeEn": "Tanegashima Araki Hotel / Nishinoomote Civic Hall, Nishinoomote, Japan",
    "placeJa": "種子島あらきホテル・西之表市民会館 (西之表市, 鹿児島県)",
    "url": null
  },
  {
    "year": "2018",
    "date": "2018/9/21",
    "titleEn": "Temperature Profile Depending on Nonideal Magnetohyodrodynamic Effects in Protoplanetary Disks",
    "titleJa": "原始惑星系円盤中の非理想磁気流体学効果に依存する温度構造",
    "authorsEn": "S. Mori, X. Bai, S. Okuzumi",
    "authorsJa": "森 昇志, X. Bai, 奥住 聡",
    "confEn": "The Astronomical Society of Japan 2018 Fall Meeting",
    "confJa": "天文学会 2018年秋季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "University of Hyogo, Himeji, Japan",
    "placeJa": "兵庫県立大学 (姫路)",
    "url": "https://www.asj.or.jp/nenkai/archive/2018b/prog.pdf"
  },
  {
    "year": "2018",
    "date": "2018/ 9/10-11",
    "titleEn": "Magnetohydrodynamic Simulation for Temperature Structure of Circumplanetary Disks",
    "titleJa": "磁気流体学計算から探る周惑星円盤の温度構造",
    "authorsEn": "S. Mori, Y. Shibaike",
    "authorsJa": "森 昇志, 芝池 諭人",
    "confEn": "Planetary formation debate: from protoplanetary disk to giant impact",
    "confJa": "惑星形成討論会:原始惑星系円盤から惑星巨大衝突まで",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Tohoku University, Sendai, Japan",
    "placeJa": "東北大学 (仙台)",
    "url": null
  },
  {
    "year": "2018",
    "date": "2018/ 8/30-31",
    "titleEn": "Efficiency of Accretion Heating in Circumplanetary Disks",
    "titleJa": "Efficiency of Accretion Heating in Circumplanetary Disks",
    "authorsEn": "S. Mori, Y. Shibaike",
    "authorsJa": "森 昇志, 芝池 諭人",
    "confEn": "Satellite system workshop",
    "confJa": "衛星系研究会",
    "type": "poster",
    "scope": "domestic",
    "placeEn": "Tokyo Institute of Technology, Meguro, Japan",
    "placeJa": "東京工業大学 (目黒)",
    "url": "https://www.cps-jp.org/~satellite/index6.html"
  },
  {
    "year": "2018",
    "date": "2018/5/20-24",
    "titleEn": "Temperature Structure of Weakly Ionized Protoplanetary Disks",
    "titleJa": "Temperature Structure of Weakly Ionized Protoplanetary Disks",
    "authorsEn": "S. Mori, X. Bai, S. Okuzumi",
    "authorsJa": "森 昇志, X. Bai, 奥住 聡",
    "confEn": "Japan Geoscience Union Meeting 2018",
    "confJa": "日本地球惑星科学連合2018年大会",
    "type": "poster",
    "scope": "domestic",
    "placeEn": "Makuhari Messe, Chiba, Japan",
    "placeJa": "幕張メッセ (千葉)",
    "url": "http://www.jpgu.org/meeting_2018/",
    "noteEn": "Geofut18 2nd place winner",
    "noteJa": "Geofut18 第２位"
  },
  {
    "year": "2018",
    "date": "2018/3/26-30",
    "titleEn": "Efficiency of Viscous Heating in Circumplanetary Disks",
    "titleJa": "Efficiency of Viscous Heating in Circumplanetary Disks",
    "authorsEn": "S. Mori, Y. Shibaike",
    "authorsJa": "森 昇志, 芝池 諭人",
    "confEn": "Circumplanetary Disks and Satellite Formation",
    "confJa": "Circumplanetary Disks and Satellite Formation",
    "type": "poster",
    "scope": "international",
    "placeEn": "Nagoya University, Nagoya, Japan",
    "placeJa": "名古屋大学 (名古屋)",
    "url": "https://cpdsf2018.wixsite.com/home"
  },
  {
    "year": "2017",
    "date": "2017/ 9/26-30",
    "titleEn": "Accretion Heating in Protoplanetary Disks based on MHD Simulations",
    "titleJa": "磁気流体計算に基づいた原始惑星系円盤の降着加熱",
    "authorsEn": "S. Mori, X. Bai, S. Okuzumi",
    "authorsJa": "森 昇志, X. Bai, 奥住 聡",
    "confEn": "The Japanese Society for Planetary Science 2017 Fall Meeting",
    "confJa": "日本惑星科学会 2017年 秋季講演会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Osaka University, Suita, Japan",
    "placeJa": "大阪大学 (吹田市, 大阪)",
    "url": "https://www.wakusei.jp/meetings/fallmeeting/2017/index.html"
  },
  {
    "year": "2017",
    "date": "2017/ 7/25-28",
    "titleEn": "Snowline depending on MHD structure in Protoplanetary Disks",
    "titleJa": "原始惑星系円盤において磁気流体構造に依存するスノーライン",
    "authorsEn": "S. Mori, X. Bai, S. Okuzumi",
    "authorsJa": "森 昇志, X. Bai, 奥住 聡",
    "confEn": "47th Summer School on Astronomy and Astrophysics for Young Astronomers",
    "confJa": "2017年度 第47回 天文・天体物理若手夏の学校",
    "type": "poster",
    "scope": "domestic",
    "placeEn": "Hotel Maruyamaso, Chikuma, Japan",
    "placeJa": "ホテル圓山荘 (千曲市, 長野)",
    "url": "http://www.astro-wakate.sakura.ne.jp/ss2017/web/",
    "posterUrl": "files/posters/poster-20170725-summer-school-snowline-mhd-structure.pdf",
    "noteEn": "Poster Presentation Award",
    "noteJa": "ポスターアワード受賞（２位）"
  },
  {
    "year": "2017",
    "date": "2017/7/10-12",
    "titleEn": "Heating Gas in Magnetic-Wind-Driven Accretion Disks",
    "titleJa": "磁気円盤風駆動降着におけるガスの加熱",
    "authorsEn": "S. Mori, X. Bai, S. Okuzumi",
    "authorsJa": "森 昇志, X. Bai, 奥住 聡",
    "confEn": "Yukawa Institute Conference \"Protoplanetary Disk\"",
    "confJa": "基研研究会「原始惑星系円盤」",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Kyoto (Japan)",
    "placeJa": "京都大学",
    "url": "http://www2.yukawa.kyoto-u.ac.jp/\\~ppds2017/"
  },
  {
    "year": "2017",
    "date": "2017/ 5/21-25",
    "titleEn": "Position of Snow Line Depending on Spatial Distribution of Magnetorotational Instability in Protoplanetary Disks",
    "titleJa": "磁気回転不安定性の空間分布に依存するスノーラインの位置",
    "authorsEn": "S. Mori, X. Bai, S. Okuzumi",
    "authorsJa": "森 昇志, X. Bai, 奥住 聡",
    "confEn": "Japan Geoscience Union Meeting 2017",
    "confJa": "日本地球惑星科学連合2017年大会",
    "type": "poster",
    "scope": "domestic",
    "placeEn": "Makuhari Messe, Chiba, Japan",
    "placeJa": "幕張メッセ (千葉)",
    "url": "http://www.jpgu.org/meeting_2017/",
    "noteEn": "Geofut17 4th place winner",
    "noteJa": "Geofut17 第４位"
  },
  {
    "year": "2017",
    "date": "2017/3/15",
    "titleEn": "Suppression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks: Validation by MHD Simulation",
    "titleJa": "原始惑星系円盤における電子加熱による磁気乱流の抑制 : 磁気流体数値計算による検証",
    "authorsEn": "S. Mori, T. Muranushi, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 村主 崇之, 奥住 聡, 犬塚 修一郎",
    "confEn": "The Astronomical Society of Japan 2017 Spring Meeting",
    "confJa": "天文学会 2017年春季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Kyushu University, Fukuoka, Japan",
    "placeJa": "九州大学 (福岡市, 福岡県)",
    "url": "https://www.asj.or.jp/nenkai/archive/2017a/session-P2.html"
  },
  {
    "year": "2016",
    "date": "2016/9/25-30",
    "titleEn": "Heating by Wind-driven Accretion in PPDs: Snowline Controlled by Hall Effect",
    "titleJa": "Heating by Wind-driven Accretion in PPDs: Snowline Controlled by Hall Effect",
    "authorsEn": "S. Mori, S. Okuzumi",
    "authorsJa": "森 昇志, 奥住 聡",
    "confEn": "Japan-Germany planet & disk workshop",
    "confJa": "Japan-Germany planet & disk workshop",
    "type": "poster",
    "scope": "international",
    "placeEn": "Beach Hotel Sunshine, Ishigaki Island, Japan",
    "placeJa": "ビーチホテルサンシャイン (石垣島, 沖縄県)",
    "url": null
  },
  {
    "year": "2016",
    "date": "2016/9/12-14",
    "titleEn": "Suppression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks",
    "titleJa": "電子加熱による原始惑星系円盤の磁気乱流の抑制",
    "authorsEn": "S. Mori, T. Muranushi, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 村主 崇之, 奥住 聡, 犬塚 修一郎",
    "confEn": "The Japanese Society for Planetary Science 2016 Fall Meeting",
    "confJa": "日本惑星科学会 2016年 秋季講演会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Notre Dame Seishin University, Okayama, Japan",
    "placeJa": "ノートルダム清心女子大学 (岡山市, 岡山県)",
    "url": "https://www.wakusei.jp/meetings/fallmeeting/2016/index.html",
    "noteEn": "Proxied by S. Okuzumi due to leg fracture",
    "noteJa": "骨折により代理発表(奥住)"
  },
  {
    "year": "2016",
    "date": "2016/7/26-29",
    "titleEn": "Supression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks",
    "titleJa": "電子加熱による原始惑星系円盤中の磁気乱流の抑制",
    "authorsEn": "S. Mori, T. Muranushi, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 村主 崇之, 奥住 聡, 犬塚 修一郎",
    "confEn": "2016 46th Summer School on Astronomy and Astrophysics for Young Astronomers",
    "confJa": "2016年度 第46回 天文・天体物理若手夏の学校",
    "type": "poster",
    "scope": "domestic",
    "placeEn": "Hotel Maruyamaso, Chikuma, Japan",
    "placeJa": "ホテル圓山荘 (千曲市, 長野)",
    "url": "http://www.astro-wakate.sakura.ne.jp/ss2016/web/",
    "posterUrl": "files/posters/poster-20160726-summer-school-electron-heating-magnetic-turbulence.pdf",
    "noteEn": "Poster Presentation Award",
    "noteJa": "ポスターアワード受賞（２位）"
  },
  {
    "year": "2016",
    "date": "2016/4/18-22",
    "titleEn": "Suppression of MRI Turbulence by Electron Heating in Protoplanetary Disks",
    "titleJa": "Suppression of MRI Turbulence by Electron Heating in Protoplanetary Disks",
    "authorsEn": "S. Mori, T. Muranushi, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 村主 崇之, 奥住 聡, 犬塚 修一郎",
    "confEn": "4th Session of the Sant Cugat Forum on Astrophysics",
    "confJa": "4th Session of the Sant Cugat Forum on Astrophysics",
    "type": "oral",
    "scope": "international",
    "placeEn": "Sant Cugat del Vallès, Barcelona, Spain",
    "placeJa": "サン・クガ・ダル・バリェス (スペイン)",
    "url": "http://www.ice.csic.es/research/forum/Forum/2016a.html"
  },
  {
    "year": "2016",
    "date": "2016/3/14-17",
    "titleEn": "Suppression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks: Validation by MHD Simulation",
    "titleJa": "原始惑星系円盤における電子加熱による磁気乱流の抑制 : 磁気流体数値計算による検証",
    "authorsEn": "S. Mori, T. Muranushi, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 村主 崇之, 奥住 聡, 犬塚 修一郎",
    "confEn": "The Astronomical Society of Japan 2016 Spring Meeting",
    "confJa": "天文学会 2016年春季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Tokyo Metropolitan University, Hachioji, Japan",
    "placeJa": "東京都立大学 (八王子市, 東京)",
    "url": "http://www.asj.or.jp/nenkai/archive/2016a/prog.pdf"
  },
  {
    "year": "2016",
    "date": "2016/ 3/14-17",
    "titleEn": "Electron Heating by Strong Electric Field Induced by Magnetic Turbulence and Its Effect on Protoplanetary Disks",
    "titleJa": "磁気乱流由来の強電場による電子の加熱が原始惑星系円盤に与える影響",
    "authorsEn": "S. Mori, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 奥住 聡, 犬塚 修一郎",
    "confEn": "The Astronomical Society of Japan 2016 Spring Meeting",
    "confJa": "天文学会 2016年春季年会",
    "type": "poster",
    "scope": "domestic",
    "placeEn": "Tokyo Metropolitan University, Hachioji, Japan",
    "placeJa": "東京都立大学 (八王子市, 東京)",
    "url": "http://www.asj.or.jp/nenkai/archive/2016a/prog.pdf"
  },
  {
    "year": "2016",
    "date": "2016/2/21-24",
    "titleEn": "Suppression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks",
    "titleJa": "Suppression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks",
    "authorsEn": "S. Mori, T. Muranushi, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 村主 崇之, 奥住 聡, 犬塚 修一郎",
    "confEn": "Exoplanets and Disks: Their Formation and Diversity III",
    "confJa": "Exoplanets and Disks: Their Formation and Diversity III",
    "type": "poster",
    "scope": "international",
    "placeEn": "Hotel Nikko Yaeyama, Ishigaki Island, Japan",
    "placeJa": "ホテル日航八重山 (石垣島, 沖縄県)",
    "url": "https://exoplanets.astron.s.u-tokyo.ac.jp/WS2015/program_e.html"
  },
  {
    "year": "2015",
    "date": "2015/10/14-16",
    "titleEn": "Gravitational Instability Induced by Suppressing Turbulence by Electron Heating: The Effect of Stellar X-Rays",
    "titleJa": "電子加熱の磁気乱流の抑制が引き起こす重力不安定：中心星X線が与える影響",
    "authorsEn": "S. Mori, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 奥住 聡, 犬塚 修一郎",
    "confEn": "The Japanese Society for Planetary Science 2015 Fall Meeting",
    "confJa": "日本惑星科学会 2015年 秋季講演会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Tokyo (Japan)",
    "placeJa": "東京工業大学(東京)",
    "url": "https://www.wakusei.jp/meetings/fallmeeting/2015/index.html"
  },
  {
    "year": "2015",
    "date": "2015/ 9/29-10/2",
    "titleEn": "The Effect of Electron Heating on Magnetorotational Turbulence in PPDs: Self-Regulation and Reduced Turbulence Strength",
    "titleJa": "The Effect of Electron Heating on Magnetorotational Turbulence in PPDs: Self-Regulation and Reduced Turbulence Strength",
    "authorsEn": "S. Mori, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 奥住 聡, 犬塚 修一郎",
    "confEn": "Protoplanetary Disk Dynamics and Planet Formation",
    "confJa": "Protoplanetary Disk Dynamics and Planet Formation",
    "type": "oral",
    "scope": "international",
    "placeEn": "JAMSTEC, Yokohama, Japan",
    "placeJa": "JAMSTEC (横浜市, 神奈川県)",
    "url": "https://sites.google.com/site/ppdisk2015/"
  },
  {
    "year": "2015",
    "date": "2015/9/9-11",
    "titleEn": "Gravitational Instability Induced by Suppressing Magnetic Turbulence by Electron Heating",
    "titleJa": "電子加熱による磁気乱流の抑制が引き起こす遠方の重力不安定",
    "authorsEn": "S. Mori, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 奥住 聡, 犬塚 修一郎",
    "confEn": "The Astronomical Society of Japan 2015 Fall Meeting",
    "confJa": "天文学会 2015年秋季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Konan University, Kobe, Japan",
    "placeJa": "甲南大学 (神戸市, 兵庫県)",
    "url": "http://www.asj.or.jp/nenkai/archive/2015b/prog.pdf"
  },
  {
    "year": "2015",
    "date": "2015/ 7/27-30",
    "titleEn": "Effects of Electron Heating on Protoplanetary Disks",
    "titleJa": "電子加熱が原始惑星系円盤に与える影響",
    "authorsEn": "S. Mori, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 奥住 聡, 犬塚 修一郎",
    "confEn": "2015 45th Summer School on Astronomy and Astrophysics for Young Astronomers",
    "confJa": "2015年度 第45回 天文・天体物理若手夏の学校",
    "type": "poster",
    "scope": "domestic",
    "placeEn": "Hotel Maruyamaso, Chikuma, Japan",
    "placeJa": "ホテル圓山荘 (千曲市, 長野)",
    "url": "http://astro-wakate.sakura.ne.jp/ss2015/web/",
    "posterUrl": "files/posters/poster-20150727-summer-school-effects-of-electron-heating.pdf",
    "noteEn": "Poster Presentation Award",
    "noteJa": "ポスターアワード受賞（２位）"
  },
  {
    "year": "2015",
    "date": "2015/ 6/1-4",
    "titleEn": "Electron Heating and Suppression of Magnetorotational Turbulence in Protoplanetary Disks",
    "titleJa": "Electron Heating and Suppression of Magnetorotational Turbulence in Protoplanetary Disks",
    "authorsEn": "S. Mori, S. Okuzumi, S. Inutsuka",
    "authorsJa": "森 昇志, 奥住 聡, 犬塚 修一郎",
    "confEn": "3rd DTA Symposium",
    "confJa": "3rd DTA Symposium",
    "type": "oral",
    "scope": "international",
    "placeEn": "NAOJ, Mitaka, Japan",
    "placeJa": "国立天文台 (三鷹)",
    "url": "http://th.nao.ac.jp/meeting/dta2015a_planet/"
  },
  {
    "year": "2015",
    "date": "2015/5/24-28",
    "titleEn": "Gravitational Instability Caused by Suppressing Magnetic Turbulence by Electric-Field Heating",
    "titleJa": "電場加熱による磁気乱流の抑制が引き起こす重力不安定",
    "authorsEn": "S. Mori, S. Okuzumi",
    "authorsJa": "森 昇志, 奥住 聡",
    "confEn": "Japan Geoscience Union Meeting 2015",
    "confJa": "日本地球惑星科学連合2015年大会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Makuhari Messe, Chiba, Japan",
    "placeJa": "幕張メッセ (千葉)",
    "url": "http://www.jpgu.org/meeting_2015/"
  },
  {
    "year": "2015",
    "date": "2015/2/16-17",
    "titleEn": "Suppressing MRI Turbulence by Electric-Field Heating of Electrons",
    "titleJa": "電子の電場加熱による磁気回転乱流の抑制",
    "authorsEn": "S. Mori, S. Okuzumi",
    "authorsJa": "森 昇志, 奥住 聡",
    "confEn": "Grant-in-Aid for Scientific Research on Innovative Areas Exoplanets Group B01,B02 Meeting",
    "confJa": "新学術領域「系外惑星」B01,B02班 研究会「円盤から惑星・衛星へ：形成と進化」",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Tokyo Institute of Technology, Tokyo, Japan",
    "placeJa": "東京工業大学 (東京都)",
    "url": null
  },
  {
    "year": "2014",
    "date": "2014/11/4-7",
    "titleEn": "Plasma Heating by MRI-induced Electric Fields and Its Effect on Dust Growth in Protoplanetary Disks",
    "titleJa": "Plasma Heating by MRI-induced Electric Fields and Its Effect on Dust Growth in Protoplanetary Disks",
    "authorsEn": "S. Mori, S. Okuzumi",
    "authorsJa": "森 昇志, 奥住 聡",
    "confEn": "Japan-German Meeting",
    "confJa": "Japan-German Meeting",
    "type": "poster",
    "scope": "international",
    "placeEn": "MPIA, Heidelberg, Germany",
    "placeJa": "MPIA (ハイデルベルグ, ドイツ)",
    "url": "http://www.mpia.de/PSF/PSFpages/Theory/HDJap2014/"
  },
  {
    "year": "2014",
    "date": "2014/9/24-26",
    "titleEn": "Electric Field Heating of Plasma in Magnetic Turbulence: Effects on Turbulence Strength and Dust Growth",
    "titleJa": "円盤磁気乱流中でのプラズマの電場加熱：磁気乱流強度とダスト成長への影響",
    "authorsEn": "S. Mori, S. Okuzumi",
    "authorsJa": "森 昇志, 奥住 聡",
    "confEn": "The Japanese Society for Planetary Science 2014 Fall Meeting",
    "confJa": "日本惑星科学会 2014年 秋季講演会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Tohoku University, Sendai, Japan",
    "placeJa": "東北大学 (仙台市, 宮城県)",
    "url": "https://www.wakusei.jp/meetings/fallmeeting/2014/index.html"
  },
  {
    "year": "2014",
    "date": "2014/ 9/11-13",
    "titleEn": "Amplifying Ohmic Dissipation by Developed Magnetic Turbulence in Protoplanetary Disks",
    "titleJa": "原始惑星系円盤の成長した磁気乱流によるオーム散逸の増幅",
    "authorsEn": "S. Mori, S. Okuzumi",
    "authorsJa": "森 昇志, 奥住 聡",
    "confEn": "The Astronomical Society of Japan 2014 Fall Meeting",
    "confJa": "天文学会 2014年秋季年会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Yamagata University, Yamagata, Japan",
    "placeJa": "山形大学 (山形市, 山形県)",
    "url": "http://ksirius.kj.yamagata-u.ac.jp/~asj14fall/"
  },
  {
    "year": "2014",
    "date": "2014/ 8/4-8",
    "titleEn": "Interplay between dust and MHD turbulence in protoplanetary disks: electric-field heating of plasmas and its effect on the ionization balance of dusty disks",
    "titleJa": "Interplay between dust and MHD turbulence in protoplanetary disks: electric-field heating of plasmas and its effect on the ionization balance of dusty disks",
    "authorsEn": "S. Mori, S. Okuzumi",
    "authorsJa": "森 昇志, 奥住 聡",
    "confEn": "The 7th meeting on Cosmic dust",
    "confJa": "The 7th meeting on Cosmic dust",
    "type": "poster",
    "scope": "international",
    "placeEn": "Umeda, Osaka, Japan",
    "placeJa": "梅田 (大阪市, 大阪府)",
    "url": "https://www.cps-jp.org/~dust/Welcome_VII.html",
    "noteEn": "Poster Presentation Award",
    "noteJa": "ポスターアワード受賞"
  },
  {
    "year": "2014",
    "date": "2014/7/28-31",
    "titleEn": "Electron Heating and Decreasing of Ionization Fraction by Magnetic Turbulence in Protoplanetary Disks",
    "titleJa": "原子惑星系円盤の磁気乱流による電子の加熱と電離度の減少",
    "authorsEn": "S. Mori, S. Okuzumi",
    "authorsJa": "森 昇志, 奥住 聡",
    "confEn": "2014 44th Summer School on Astronomy and Astrophysics for Young Astronomers",
    "confJa": "2014年度 第44回 天文・天体物理若手夏の学校",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Hotel Maruyamaso, Chikuma, Japan",
    "placeJa": "ホテル圓山荘 (千曲市, 長野)",
    "url": "http://www.astro-wakate.sakura.ne.jp/ss2014/web/"
  },
  {
    "year": "2014",
    "date": "2014/ 4/28-5/2",
    "titleEn": "Dead Zones by Electric-Field Heating in Protoplanetary Disks",
    "titleJa": "原始惑星系円盤における電場加熱によるデッドゾーン",
    "authorsEn": "S. Mori, S. Okuzumi",
    "authorsJa": "森 昇志, 奥住 聡",
    "confEn": "Japan Geoscience Union Meeting 2014",
    "confJa": "日本地球惑星科学連合2014年大会",
    "type": "oral",
    "scope": "domestic",
    "placeEn": "Pacifico Yokohama, Yokohama, Japan",
    "placeJa": "パシフィコ横浜 (横浜)",
    "url": "http://www.jpgu.org/meeting_2014/"
  }
];
