window.presentationsData = [
  {"year": "2025", "titleEn": "Ionization, Radiation, and MHD in Protoplanetary Disks", "titleJa": "Ionization, Radiation, and MHD in Protoplanetary Disks", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "Extra Dimension in Planet Formation", "confJa": "Extra Dimension in Planet Formation", "type": "oral", "scope": "international"},
  {"year": "2025", "titleEn": "Global Nonideal MHD Simulations of Protoplanetary Disks: Episodic Surface Accretion", "titleJa": "Global Nonideal MHD Simulations of Protoplanetary Disks: Episodic Surface Accretion", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "The Astronomical Society of Japan Autumn Meeting 2025", "confJa": "日本天文学会2025年秋季年会", "type": "oral", "scope": "domestic"},
  {"year": "2025", "titleEn": "Temperature Structure and Its Evolution of Magnetized Protoplanetary Disks", "titleJa": "Temperature Structure and Its Evolution of Magnetized Protoplanetary Disks", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "Exoplanets & Planet Formation Workshop 2025", "confJa": "Exoplanets & Planet Formation Workshop 2025", "type": "oral", "scope": "international"},
  {"year": "2025", "titleEn": "Magnetic Circumplanetary Disks", "titleJa": "Magnetic Circumplanetary Disks", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "Circumplanetary and Satellite System Workshop 2025", "confJa": "Circumplanetary and Satellite System Workshop 2025", "type": "oral", "scope": "international"},
  {"year": "2024", "titleEn": "Long-term Thermal Evolution of Magnetized Protoplanetary Disks with Mass Loss: Impact on Super-Earth Formation", "titleJa": "Long-term Thermal Evolution of Magnetized Protoplanetary Disks with Mass Loss: Impact on Super-Earth Formation", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "The Japanese Society for Planetary Sciences Autumn Meeting 2024", "confJa": "日本惑星科学会 2024年 秋季講演会", "type": "oral", "scope": "domestic"},
  {"year": "2024", "titleEn": "Magnetized Protoplanetary Disks", "titleJa": "Magnetized Protoplanetary Disks", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "Simulating Physics in Celestial Ecosystem", "confJa": "Simulating Physics in Celestial Ecosystem", "type": "invited", "scope": "international"},
  {"year": "2023", "titleEn": "Temperature Structure of Magnetized Protoplanetary Disks", "titleJa": "Temperature Structure of Magnetized Protoplanetary Disks", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "Exoplanets & Planet Formation Workshop 2023", "confJa": "Exoplanets & Planet Formation Workshop 2023", "type": "poster", "scope": "international"},
  {"year": "2023", "titleEn": "Radiative Nonideal MHD Simulations of Inner Protoplanetary Disks", "titleJa": "Radiative Nonideal MHD Simulations of Inner Protoplanetary Disks", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "Magnetohydrodynamical Flows in Young Circumstellar Disks", "confJa": "Magnetohydrodynamical Flows in Young Circumstellar Disks", "type": "oral", "scope": "international"},
  {"year": "2023", "titleEn": "Thermal Structure of Inner Magnetized Disks: Radiative Nonideal MHD Simulations", "titleJa": "Thermal Structure of Inner Magnetized Disks: Radiative Nonideal MHD Simulations", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "The Astronomical Society of Japan Autumn Meeting 2023", "confJa": "日本天文学会2023年秋季年会", "type": "oral", "scope": "domestic"},
  {"year": "2023", "titleEn": "Nonideal MHD Simulations to Understand the Temperature Structure of Protoplanetary Disks", "titleJa": "Nonideal MHD Simulations to Understand the Temperature Structure of Protoplanetary Disks", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "SPIDI23: The Inner Disk of Young Stars – Accretion, Ejection, and Planet Formation", "confJa": "SPIDI23: The Inner Disk of Young Stars – Accretion, Ejection, and Planet Formation", "type": "poster", "scope": "international"},
  {"year": "2023", "titleEn": "Radiative Nonideal MHD Simulations of the Inner Protoplanetary Disks", "titleJa": "Radiative Nonideal MHD Simulations of the Inner Protoplanetary Disks", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "Protostars and Planets VII", "confJa": "Protostars and Planets VII", "type": "poster", "scope": "international"},
  {"year": "2023", "titleEn": "Numerical Simulations of Protoplanetary Disks to Elucidate Planet Formation Processes: Current Status and Future Prospects", "titleJa": "Numerical Simulations of Protoplanetary Disks to Elucidate Planet Formation Processes: Current Status and Future Prospects", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "CfCA Users Meeting 2022", "confJa": "CfCA Users Meeting 2022", "type": "invited", "scope": "domestic"},
  {"year": "2022", "titleEn": "Temperature Structure from Global Nonideal MHD Simulations of Protoplanetary Disks", "titleJa": "Temperature Structure from Global Nonideal MHD Simulations of Protoplanetary Disks", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "The Astronomical Society of Japan Spring Meeting 2022", "confJa": "日本天文学会2022年春季年会", "type": "oral", "scope": "domestic"},
  {"year": "2021", "titleEn": "Modeling Magnetic Circumplanetary Disks: Wind-driven Accretion Regions", "titleJa": "Modeling Magnetic Circumplanetary Disks: Wind-driven Accretion Regions", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "The Astronomical Society of Japan Autumn Meeting 2021", "confJa": "日本天文学会2021年秋季年会", "type": "oral", "scope": "domestic"},
  {"year": "2020", "titleEn": "Magnetic Accretion and Snowline Migration in Protoplanetary Disks", "titleJa": "Magnetic Accretion and Snowline Migration in Protoplanetary Disks", "authorsEn": "S. Mori", "authorsJa": "森 昇志", "confEn": "The Japanese Society for Planetary Sciences Autumn Meeting 2020", "confJa": "日本惑星科学会 2020年 秋季講演会", "type": "oral", "scope": "domestic"},

  { year: "2020",
    titleEn: "Mock Observations of Rotating Infalling Envelopes Based on Hydrodynamics: Estimating Central Stellar Mass", 
    titleJa: "流体力学に基づいた回転降着エンベロープの模擬観測:中心星質量の推定",
    authorsEn: "S. Mori, Y. Aikawa, R. Oya, S. Yamamoto", authorsJa: "森 昇志, 相川 祐理, 大屋瑤子, 山本智",
    confEn: "The Astronomical Society of Japan 2020 Autumn Meeting", confJa: "日本天文学会2020年秋季年会",
    type: "oral", scope: "domestic" },
  { year: "2020",
    titleEn: "Evolution of the Water Snowline in Magnetized Protoplanetary Disks", titleJa: "Evolution of the Water Snowline in Magnetized Protoplanetary Disks",
    authorsEn: "S. Mori, S. Okuzumi, M. Kunitomo, X. Bai", authorsJa: "森 昇志, 奥住 聡, 國友 正信, X. Bai",
    confEn: "Building Blocks of Planets 2020", confJa: "Building Blocks of Planets 2020",
    type: "oral", scope: "international" },
  { year: "2020",
    titleEn: "SPICA Observation of Water Emission Reveals Thermal and Dynamical Structures of Protoplanetary Disks", titleJa: "SPICAの水輝線観測が明らかにする原始惑星系円盤の熱･力学構造",
    authorsEn: "S. Mori, SPICA planet formation working group", authorsJa: "森 昇志, SPICAワーキンググループ",
    confEn: "The Astronomical Society of Japan 2020 Spring Meeting", confJa: "日本天文学会2020年春季年会",
    type: "oral", scope: "domestic" },
  { year: "2019",
    titleEn: "Physical Interpretation of Line Observations of Envelope and Disk Systems: A Case of L1527", titleJa: "Physical interpretation of line observations of envelope and disk systems: a case of L1527",
    authorsEn: "S. Mori, Y. Aikawa", authorsJa: "森 昇志, 相川 祐理",
    confEn: "ALMA workshop 2019: Early Planet Formation in Embedded Disks", confJa: "ALMA workshop 2019: Early Planet Formation in Embedded Disks",
    type: "oral", scope: "international" },
  { year: "2019",
    titleEn: "Evolution of the Water Snowline in Magnetized Protoplanetary Disks", titleJa: "Evolution of the Water Snowline in Magnetized Protoplanetary Disks",
    authorsEn: "S. Mori, S. Okuzumi, M. Kunitomo, X. Bai", authorsJa: "森 昇志, 奥住 聡, 國友 正信, X. Bai",
    confEn: "PLANET FORMATION WORKSHOP 2019", confJa: "PLANET FORMATION WORKSHOP 2019",
    type: "oral", scope: "international" },
  { year: "2019",
    titleEn: "Evolution of the Water Snowline in Magnetized Protoplanetary Disks", titleJa: "Evolution of the Water Snowline in Magnetized Protoplanetary Disks",
    authorsEn: "S. Mori, S. Okuzumi, M. Kunitomo, X. Bai", authorsJa: "森 昇志, 奥住 聡, 國友 正信, X. Bai",
    confEn: "EXTREME SOLAR SYSTEMS IV", confJa: "EXTREME SOLAR SYSTEMS IV",
    type: "poster", scope: "international" },
  { year: "2019",
    titleEn: "Inefficient Magnetic Accretion Heating in Protoplanetary Disks", titleJa: "Inefficient Magnetic Accretion Heating in Protoplanetary Disks",
    authorsEn: "S. Mori, S. Okuzumi, X. Bai", authorsJa: "森 昇志, 奥住 聡, X. Bai",
    confEn: "Ringberg Workshop: Turbulence and Structure Formation in Protoplanetary Disks 2019", confJa: "Ringberg Workshop: Turbulence and Structure Formation in Protoplanetary Disks 2019",
    type: "oral", scope: "international" },
  { year: "2019",
    titleEn: "Inefficient Magnetic Accretion Heating in Protoplanetary Disks", titleJa: "Inefficient Magnetic Accretion Heating in Protoplanetary Disks",
    authorsEn: "S. Mori, S. Okuzumi, X. Bai", authorsJa: "森 昇志, 奥住 聡, X. Bai",
    confEn: "From Stars to Planets II - Connecting our understanding of star and planet formation", confJa: "From Stars to Planets II - Connecting our understanding of star and planet formation",
    type: "oral", scope: "international" },
  { year: "2019",
    titleEn: "Inefficient Accretion Heating in Protoplanetary Disks: Influence on Evolution of Snow Line", titleJa: "原始惑星系円盤の非効率な降着加熱:スノーラインの進化への影響",
    authorsEn: "S. Mori, X. Bai, S. Okuzumi", authorsJa: "森 昇志, X. Bai, 奥住 聡",
    confEn: "Japan Geoscience Union Meeting 2019", confJa: "日本地球惑星科学連合2019年大会",
    type: "oral", scope: "domestic" },
  { year: "2018",
    titleEn: "Inefficient Heating by Wind-driven Accretion in Protoplanetary Disks", titleJa: "Inefficient Heating by Wind-driven Accretion in Protoplanetary Disks",
    authorsEn: "S. Mori, X. Bai, S. Okuzumi", authorsJa: "森 昇志, X. Bai, 奥住 聡",
    confEn: "Japanese-German meeting on Exoplanets and Planet Formation 2018", confJa: "Japanese-German meeting on Exoplanets and Planet Formation 2018",
    type: "oral", scope: "international" },
  { year: "2018",
    titleEn: "Wind-driven Accretion in Circumplanetary Disks", titleJa: "Wind-driven Accretion in Circumplanetary Disks",
    authorsEn: "S. Mori, Y. Shibaike", authorsJa: "森 昇志, 芝池 諭人",
    confEn: "Planetary and Satellite System Workshop 2019", confJa: "惑星・衛星系研究会 2019",
    type: "oral", scope: "international" },
  { year: "2018",
    titleEn: "Temperature Profile Depending on Nonideal Magnetohyodrodynamic Effects in Protoplanetary Disks", titleJa: "原始惑星系円盤中の非理想磁気流体力学効果に依存する温度構造",
    authorsEn: "S. Mori, X. Bai, S. Okuzumi", authorsJa: "森 昇志, X. Bai, 奥住 聡",
    confEn: "The Astronomical Society of Japan 2018 Fall Meeting", confJa: "天文学会 2018年秋季年会",
    type: "oral", scope: "domestic" },
  { year: "2018",
    titleEn: "Magnetohydrodynamic Simulation for Temperature Structure of Circumplanetary Disks", titleJa: "磁気流体力学計算から探る周惑星円盤の温度構造",
    authorsEn: "S. Mori, Y. Shibaike", authorsJa: "森 昇志, 芝池 諭人",
    confEn: "Planetary formation debate: from protoplanetary disk to giant impact", confJa: "惑星形成討論会:原始惑星系円盤から惑星巨大衝突まで",
    type: "oral", scope: "domestic" },
  { year: "2018",
    titleEn: "Efficiency of Accretion Heating in Circumplanetary Disks", titleJa: "Efficiency of Accretion Heating in Circumplanetary Disks",
    authorsEn: "S. Mori, Y. Shibaike", authorsJa: "森 昇志, 芝池 諭人",
    confEn: "Satellite system workshop", confJa: "衛星系研究会",
    type: "poster", scope: "domestic" },
  { year: "2018",
    titleEn: "Temperature Structure of Weakly Ionized Protoplanetary Disks", titleJa: "Temperature Structure of Weakly Ionized Protoplanetary Disks",
    authorsEn: "S. Mori, X. Bai, S. Okuzumi", authorsJa: "森 昇志, X. Bai, 奥住 聡",
    confEn: "Japan Geoscience Union Meeting 2018", confJa: "日本地球惑星科学連合2018年大会",
    type: "poster", scope: "domestic", noteEn: "Geofut18 2nd place winner", noteJa: "Geofut18 第２位" },
  { year: "2018",
    titleEn: "Efficiency of Viscous Heating in Circumplanetary Disks", titleJa: "Efficiency of Viscous Heating in Circumplanetary Disks",
    authorsEn: "S. Mori, Y. Shibaike", authorsJa: "森 昇志, 芝池 諭人",
    confEn: "Circumplanetary Disks and Satellite Formation", confJa: "Circumplanetary Disks and Satellite Formation",
    type: "poster", scope: "international" },
  { year: "2017",
    titleEn: "Accretion Heating in Protoplanetary Disks based on MHD Simulations", titleJa: "磁気流体計算に基づいた原始惑星系円盤の降着加熱",
    authorsEn: "S. Mori, X. Bai, S. Okuzumi", authorsJa: "森 昇志, X. Bai, 奥住 聡",
    confEn: "The Japanese Society for Planetary Science 2017 Fall Meeting", confJa: "日本惑星科学会 2017年 秋季講演会",
    type: "oral", scope: "domestic" },
  { year: "2017",
    titleEn: "Snowline depending on MHD structure in Protoplanetary Disks", titleJa: "原始惑星系円盤において磁気流体構造に依存するスノーライン",
    authorsEn: "S. Mori, X. Bai, S. Okuzumi", authorsJa: "森 昇志, X. Bai, 奥住 聡",
    confEn: "47th Summer School on Astronomy and Astrophysics for Young Astronomers", confJa: "2017年度 第47回 天文・天体物理若手夏の学校",
    type: "poster", scope: "domestic", noteEn: "Poster Presentation Award", noteJa: "ポスターアワード受賞（２位）" },
  { year: "2017",
    titleEn: "Heating Gas in Magnetic-Wind-Driven Accretion Disks", titleJa: "磁気円盤風駆動降着におけるガスの加熱",
    authorsEn: "S. Mori, X. Bai, S. Okuzumi", authorsJa: "森 昇志, X. Bai, 奥住 聡",
    confEn: "Yukawa Institute Conference \"Protoplanetary Disk\"", confJa: "基研研究会「原始惑星系円盤」",
    type: "oral", scope: "domestic" },
  { year: "2017",
    titleEn: "Position of Snow Line Depending on Spatial Distribution of Magnetorotational Instability in Protoplanetary Disks", titleJa: "磁気回転不安定性の空間分布に依存するスノーラインの位置",
    authorsEn: "S. Mori, X. Bai, S. Okuzumi", authorsJa: "森 昇志, X. Bai, 奥住 聡",
    confEn: "Japan Geoscience Union Meeting 2017", confJa: "日本地球惑星科学連合2017年大会",
    type: "poster", scope: "domestic", noteEn: "Geofut17 4th place winner", noteJa: "Geofut17 第４位" },
  { year: "2017",
    titleEn: "Suppression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks: MHD Simulation with Stratified Simulation Box", titleJa: "原始惑星系円盤における電子加熱による磁気乱流の抑制: 成層構造を考慮した磁気流体数値計算",
    authorsEn: "S. Mori, S. Okuzumi", authorsJa: "森 昇志, 奥住 聡",
    confEn: "The Astronomical Society of Japan 2017 Spring Meeting", confJa: "天文学会 2017年春季年会",
    type: "poster", scope: "domestic" },
  { year: "2016",
    titleEn: "Heating by Wind-driven Accretion in PPDs: Snowline Controlled by Hall Effect", titleJa: "Heating by Wind-driven Accretion in PPDs: Snowline Controlled by Hall Effect",
    authorsEn: "S. Mori, S. Okuzumi", authorsJa: "森 昇志, 奥住 聡",
    confEn: "Japan-German planet & disk workshop", confJa: "Japan-German planet & disk workshop",
    type: "poster", scope: "international" },
  { year: "2016",
    titleEn: "Suppression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks", titleJa: "電子加熱による原始惑星系円盤の磁気乱流の抑制",
    authorsEn: "S. Mori, T. Muranushi, S. Okuzumi, S. Inutsuka", authorsJa: "森 昇志, 村主 崇之, 奥住 聡, 犬塚 修一郎",
    confEn: "The Japanese Society for Planetary Science 2016 Fall Meeting", confJa: "日本惑星科学会 2016年 秋季講演会",
    noteEn: "Proxied by S. Okuzumi due to leg fracture", noteJa: "骨折により代理発表(奥住)",
    type: "oral", scope: "domestic" },
  { year: "2016",
    titleEn: "Supression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks", titleJa: "電子加熱による原始惑星系円盤中の磁気乱流の抑制",
    authorsEn: "S. Mori, T. Muranushi, S. Okuzumi, S. Inutsuka", authorsJa: "森 昇志, 村主 崇之, 奥住 聡, 犬塚 修一郎",
    confEn: "2016 46th Summer School on Astronomy and Astrophysics for Young Astronomers", confJa: "2016年度 第46回 天文・天体物理若手夏の学校",
    noteEn: "Poster Presentation Award", noteJa: "ポスターアワード受賞（２位）",
    type: "poster", scope: "domestic" },
  { year: "2016",
    titleEn: "Suppression of MRI Turbulence by Electron Heating in Protoplanetary Disks", titleJa: "Suppression of MRI Turbulence by Electron Heating in Protoplanetary Disks",
    authorsEn: "S. Mori, T. Muranushi, S. Okuzumi, S. Inutsuka", authorsJa: "森 昇志, 村主 崇之, 奥住 聡, 犬塚 修一郎",
    confEn: "4th Session of the Sant Cugat Forum on Astrophysics", confJa: "4th Session of the Sant Cugat Forum on Astrophysics",
    type: "oral", scope: "international" },
  { year: "2016",
    titleEn: "Suppression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks: Validation by MHD Simulation", titleJa: "原始惑星系円盤における電子加熱による磁気乱流の抑制 : 磁気流体数値計算による検証",
    authorsEn: "S. Mori, T. Muranushi, S. Okuzumi, S. Inutsuka", authorsJa: "森 昇志, 村主 崇之, 奥住 聡, 犬塚 修一郎",
    confEn: "The Astronomical Society of Japan 2016 Spring Meeting", confJa: "天文学会 2016年春季年会",
    type: "oral", scope: "domestic" },
  { year: "2016",
    titleEn: "Electron Heating by Strong Electric Field Induced by Magnetic Turbulence and Its Effect on Protoplanetary Disks", titleJa: "磁気乱流由来の強電場による電子の加熱が原始惑星系円盤に与える影響",
    authorsEn: "S. Mori, S. Okuzumi, S. Inutsuka", authorsJa: "森 昇志, 奥住 聡, 犬塚 修一郎",
    confEn: "The Astronomical Society of Japan 2016 Spring Meeting", confJa: "天文学会 2016年春季年会",
    type: "poster", scope: "domestic" },
  { year: "2016",
    titleEn: "Suppression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks", titleJa: "Suppression of Magnetic Turbulence by Electron Heating in Protoplanetary Disks",
    authorsEn: "S. Mori, T. Muranushi, S. Okuzumi, S. Inutsuka", authorsJa: "森 昇志, 村主 崇之, 奥住 聡, 犬塚 修一郎",
    confEn: "Exoplanets and Disks: Their Formation and Diversity III", confJa: "Exoplanets and Disks: Their Formation and Diversity III",
    type: "poster", scope: "international" },
  { year: "2015",
    titleEn: "Gravitational Instability Induced by Suppressing Turbulence by Electron Heating: The Effect of Stellar X-Rays", titleJa: "電子加熱の磁気乱流の抑制が引き起こす重力不安定：中心星X線が与える影響",
    authorsEn: "S. Mori, S. Okuzumi, S. Inutsuka", authorsJa: "森 昇志, 奥住 聡, 犬塚 修一郎",
    confEn: "The Japanese Society for Planetary Science 2015 Fall Meeting", confJa: "日本惑星科学会 2015年 秋季講演会",
    type: "oral", scope: "domestic" },
  { year: "2015",
    titleEn: "The Effect of Electron Heating on Magnetorotational Turbulence in PPDs: Self-Regulation and Reduced Turbulence Strength", titleJa: "The Effect of Electron Heating on Magnetorotational Turbulence in PPDs: Self-Regulation and Reduced Turbulence Strength",
    authorsEn: "S. Mori, S. Okuzumi, S. Inutsuka", authorsJa: "森 昇志, 奥住 聡, 犬塚 修一郎",
    confEn: "Protoplanetary Disk Dynamics and Planet Formation", confJa: "Protoplanetary Disk Dynamics and Planet Formation",
    type: "oral", scope: "international" },
  { year: "2015",
    titleEn: "Gravitational Instability Induced by Suppressing Magnetic Turbulence by Electron Heating", titleJa: "電子加熱による磁気乱流の抑制が引き起こす遠方の重力不安定",
    authorsEn: "S. Mori, S. Okuzumi, S. Inutsuka", authorsJa: "森 昇志, 奥住 聡, 犬塚 修一郎",
    confEn: "The Astronomical Society of Japan 2015 Fall Meeting", confJa: "天文学会 2015年秋季年会",
    type: "oral", scope: "domestic" },
  { year: "2015",
    titleEn: "Effects of Electron Heating on Protoplanetary Disks", titleJa: "電子加熱が原始惑星系円盤に与える影響",
    authorsEn: "S. Mori, S. Okuzumi, S. Inutsuka", authorsJa: "森 昇志, 奥住 聡, 犬塚 修一郎",
    confEn: "2015 45th Summer School on Astronomy and Astrophysics for Young Astronomers", confJa: "2015年度 第45回 天文・天体物理若手夏の学校",
    noteEn: "Poster Presentation Award", noteJa: "ポスターアワード受賞（２位）",
    type: "poster", scope: "domestic" },
  { year: "2015",
    titleEn: "Electron Heating and Suppression of Magnetorotational Turbulence in Protoplanetary Disks", titleJa: "Electron Heating and Suppression of Magnetorotational Turbulence in Protoplanetary Disks",
    authorsEn: "S. Mori, S. Okuzumi, S. Inutsuka", authorsJa: "森 昇志, 奥住 聡, 犬塚 修一郎",
    confEn: "3rd DTA Symposium", confJa: "3rd DTA Symposium",
    type: "oral", scope: "international" },
  { year: "2015",
    titleEn: "Gravitational Instability Caused by Suppressing Magnetic Turbulence by Electric-Field Heating", titleJa: "電場加熱による磁気乱流の抑制が引き起こす重力不安定",
    authorsEn: "S. Mori, S. Okuzumi", authorsJa: "森 昇志, 奥住 聡",
    confEn: "Japan Geoscience Union Meeting 2015", confJa: "日本地球惑星科学連合2015年大会",
    type: "oral", scope: "domestic" },
  { year: "2015",
    titleEn: "Suppressing MRI Turbulence by Electric-Field Heating of Electrons", titleJa: "電子の電場加熱による磁気回転乱流の抑制",
    authorsEn: "S. Mori, S. Okuzumi", authorsJa: "森 昇志, 奥住 聡",
    confEn: "Grant-in-Aid for Scientific Research on Innovative Areas Exoplanets Group B01,B02 Meeting", confJa: "新学術領域「系外惑星」B01,B02班 研究会",
    type: "oral", scope: "domestic" },
  { year: "2014",
    titleEn: "Plasma Heating by MRI-induced Electric Fields and Its Effect on Dust Growth in Protoplanetary Disks", titleJa: "Plasma Heating by MRI-induced Electric Fields and Its Effect on Dust Growth in Protoplanetary Disks",
    authorsEn: "S. Mori, S. Okuzumi", authorsJa: "森 昇志, 奥住 聡",
    confEn: "Japan-German Meeting", confJa: "Japan-German Meeting",
    type: "poster", scope: "international" },
  { year: "2014",
    titleEn: "Electric Field Heating of Plasma in Magnetic Turbulence: Effects on Turbulence Strength and Dust Growth", titleJa: "円盤磁気乱流中でのプラズマの電場加熱：磁気乱流強度とダスト成長への影響",
    authorsEn: "S. Mori, S. Okuzumi", authorsJa: "森 昇志, 奥住 聡",
    confEn: "The Japanese Society for Planetary Science 2014 Fall Meeting", confJa: "日本惑星科学会 2014年 秋季講演会",
    type: "oral", scope: "domestic" },
  { year: "2014",
    titleEn: "Amplifying Ohmic Dissipation by Developed Magnetic Turbulence in Protoplanetary Disks", titleJa: "原始惑星系円盤の成長した磁気乱流によるオーム散逸の増幅",
    authorsEn: "S. Mori, S. Okuzumi", authorsJa: "森 昇志, 奥住 聡",
    confEn: "The Astronomical Society of Japan 2014 Fall Meeting", confJa: "天文学会 2014年秋季年会",
    type: "oral", scope: "domestic" },
  { year: "2014",
    titleEn: "Interplay between dust and MHD turbulence in protoplanetary disks: electric-field heating of plasmas and its effect on the ionization balance of dusty disks", titleJa: "Interplay between dust and MHD turbulence in protoplanetary disks: electric-field heating of plasmas and its effect on the ionization balance of dusty disks",
    authorsEn: "S. Mori, S. Okuzumi", authorsJa: "森 昇志, 奥住 聡",
    confEn: "The 7th meeting on Cosmic dust", confJa: "The 7th meeting on Cosmic dust",
    noteEn: "Poster Presentation Award", noteJa: "ポスターアワード受賞",
    type: "poster", scope: "international" },
  { year: "2014",
    titleEn: "Electron Heating and Decreasing of Ionization Fraction by Magnetic Turbulence in Protoplanetary Disks", titleJa: "原子惑星系円盤の磁気乱流による電子の加熱と電離度の減少",
    authorsEn: "S. Mori, S. Okuzumi", authorsJa: "森 昇志, 奥住 聡",
    confEn: "2014 44th Summer School on Astronomy and Astrophysics for Young Astronomers", confJa: "2015年度 第45回 天文・天体物理若手夏の学校",
    type: "oral", scope: "domestic" },
  { year: "2014",
    titleEn: "Dead Zones by Electric-Field Heating in Protoplanetary Disks", titleJa: "原始惑星系円盤における電場加熱によるデッドゾーン",
    authorsEn: "S. Mori, S. Okuzumi", authorsJa: "森 昇志, 奥住 聡",
    confEn: "Japan Geoscience Union Meeting 2014", confJa: "日本地球惑星科学連合2014年大会",
    type: "oral", scope: "domestic" }
];
