window.publicationsData = [
  {
    "year": "2025",
    "selected": true,
    "titleEn": "Radiative Nonideal Magnetohydrodynamic Simulations of Inner Protoplanetary Disks: Temperature Structures, Asymmetric Winds, and Episodic Surface Accretion",
    "titleJa": "Radiative Nonideal Magnetohydrodynamic Simulations of Inner Protoplanetary Disks: Temperature Structures, Asymmetric Winds, and Episodic Surface Accretion",
    "authorsEn": "<strong>Shoji Mori</strong>, Xue-Ning Bai, Kengo Tomida",
    "authorsJa": "<strong>森 昇志</strong>, Xue-Ning Bai, 富田 賢吾",
    "journalEn": "The Astrophysical Journal, 992:85",
    "journalJa": "The Astrophysical Journal, 992:85",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/adf8d7",
    "arxivUrl": "https://arxiv.org/abs/2508.03624",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Fadf8d7%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "This study simulates the inner part of a planet-forming disk around a young star. It finds that gas can rush inward in bursts along the disk surface and launch uneven winds, but the disk's dense middle region does not heat up much because the energy is released in thin upper layers and partly carried away by the wind.",
    "abstractJa": "若い星のまわりにある「惑星の材料の円盤」の内側をシミュレーションした研究です。ガスは円盤の表面を通って突発的に内側へ流れ込み、左右非対称な風も生みますが、エネルギーは薄い上層で放出され、さらに一部は風に運び去られるため、円盤の密な中心部はあまり熱くならないことを示しました。"
  },
  {
    "year": "2025",
    "selected": true,
    "titleEn": "Long-term evolution of the temperature structure in magnetized protoplanetary disks and its implication for the dichotomy of planetary composition",
    "titleJa": "Long-term evolution of the temperature structure in magnetized protoplanetary disks and its implication for the dichotomy of planetary composition",
    "authorsEn": "<strong>Shoji Mori</strong>, Masanobu Kunitomo, Masahiro Ogihara",
    "authorsJa": "<strong>森 昇志</strong>, 國友 正信, 荻原 正博",
    "journalEn": "Astronomy & Astrophysics, 697:A192",
    "journalJa": "Astronomy & Astrophysics, 697:A192",
    "publicationUrl": "https://doi.org/10.1051/0004-6361/202453362",
    "arxivUrl": "https://arxiv.org/abs/2504.08042",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.1051%2F0004-6361%2F202453362%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "This study follows how the temperature of a planet-forming disk changes over millions of years. It finds that, at distances where many planets form, starlight usually warms the disk more than infalling gas does, and winds can cool the disk further, which may help explain why some planets stay dry while others become rich in water.",
    "abstractJa": "惑星が生まれる円盤の温度が、長い時間の中でどう変わるかを調べた研究です。多くの惑星ができる距離では、落ち込むガスの熱よりも星の光のほうが効きやすく、さらに円盤風が温まり方を弱めるため、その違いが「乾いた惑星」と「水の多い惑星」の分かれ方につながる可能性を示しました。"
  },
  {
    "year": "2025",
    "selected": false,
    "titleEn": "Solving for the 2D water snowline with hydrodynamic simulations: Emergence of the gas outflow, water cycle, and temperature plateau",
    "titleJa": "Solving for the 2D water snowline with hydrodynamic simulations: Emergence of the gas outflow, water cycle, and temperature plateau",
    "authorsEn": "Yu Wang, Chris W. Ormel, <strong>Shoji Mori</strong>, Xue-Ning Bai",
    "authorsJa": "Yu Wang, Chris W. Ormel, <strong>森 昇志</strong>, Xue-Ning Bai",
    "journalEn": "Astronomy & Astrophysics, 696:A38",
    "journalJa": "Astronomy & Astrophysics, 696:A38",
    "publicationUrl": "https://doi.org/10.1051/0004-6361/202453036",
    "arxivUrl": "https://arxiv.org/abs/2502.08936",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.1051%2F0004-6361%2F202453036%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2024",
    "selected": false,
    "titleEn": "Early Planet Formation in Embedded Disks (eDisk). XIV. Flared Dust Distribution and Viscous Accretion Heating of the Disk around R CrA IRS 7B-a",
    "titleJa": "Early Planet Formation in Embedded Disks (eDisk). XIV. Flared Dust Distribution and Viscous Accretion Heating of the Disk around R CrA IRS 7B-a",
    "authorsEn": "Shigehisa Takakuwa, Kazuya Saigo, Miyu Kido, ..., <strong>Shoji Mori</strong>, et al.",
    "authorsJa": "Shigehisa Takakuwa, Kazuya Saigo, Miyu Kido, ..., <strong>森 昇志</strong>, ほか",
    "journalEn": "The Astrophysical Journal, 964(1):24",
    "journalJa": "The Astrophysical Journal, 964(1):24",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/ad1f57",
    "arxivUrl": "https://arxiv.org/abs/2401.08722",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Fad1f57%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2024",
    "selected": true,
    "titleEn": "Synthetic Observations of the Infalling Rotating Envelope: Links between the Physical Structure and Observational Features",
    "titleJa": "Synthetic Observations of the Infalling Rotating Envelope: Links between the Physical Structure and Observational Features",
    "authorsEn": "<strong>Shoji Mori</strong>, Yuri Aikawa, Yoko Oya, Satoshi Yamamoto, Nami Sakai",
    "authorsJa": "<strong>森 昇志</strong>, 相川 祐理, 大屋 瑶子, 山本 智, 坂井 南美",
    "journalEn": "The Astrophysical Journal, 961(1):31",
    "journalJa": "The Astrophysical Journal, 961(1):31",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/ad0634",
    "arxivUrl": "https://arxiv.org/abs/2401.06213",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Fad0634%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "We created simulated telescope data for gas that is falling and rotating around a young star, and compared it with real observations of L1527. The comparison shows that similar-looking data can come from different gas motions, and suggests the infalling gas is slower than simple models assume, which changes how we estimate the star's mass.",
    "abstractJa": "若い星のまわりで、落ち込みながら回転するガスを望遠鏡で見たらどう見えるかを計算し、L1527 の実際の観測と比べた研究です。見た目の似た観測結果でも、背後にあるガスの動き方は一通りではなく、実際の落下速度は単純なモデルより遅い可能性があるため、星の重さの見積もりも変わり得ることを示しました。"
  },
  {
    "year": "2023",
    "selected": false,
    "titleEn": "Effective Dust Growth in Laminar Circumplanetary Discs with Magnetic Wind-Driven Accretion",
    "titleJa": "Effective Dust Growth in Laminar Circumplanetary Discs with Magnetic Wind-Driven Accretion",
    "authorsEn": "Yuhito Shibaike, <strong>Shoji Mori</strong>",
    "authorsJa": "芝池 諭人, <strong>森 昇志</strong>",
    "journalEn": "Monthly Notices of the Royal Astronomical Society, 518(4):5444-5456",
    "journalJa": "Monthly Notices of the Royal Astronomical Society, 518(4):5444-5456",
    "publicationUrl": "https://doi.org/10.1093/mnras/stac3428",
    "arxivUrl": "https://arxiv.org/abs/2211.08947",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.1093%2Fmnras%2Fstac3428%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2023",
    "selected": false,
    "titleEn": "Insights on the Sun Birth Environment in the Context of Star Cluster Formation in Hub-Filament Systems",
    "titleJa": "Insights on the Sun Birth Environment in the Context of Star Cluster Formation in Hub-Filament Systems",
    "authorsEn": "Doris Arzoumanian, Sota Arakawa, Masato I. N. Kobayashi, ..., <strong>Shoji Mori</strong>, et al.",
    "authorsJa": "Doris Arzoumanian, Sota Arakawa, Masato I. N. Kobayashi, ..., <strong>森 昇志</strong>, ほか",
    "journalEn": "The Astrophysical Journal Letters, 947(2):L29",
    "journalJa": "The Astrophysical Journal Letters, 947(2):L29",
    "publicationUrl": "https://doi.org/10.3847/2041-8213/acc849",
    "arxivUrl": "https://arxiv.org/abs/2303.15695",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F2041-8213%2Facc849%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2023",
    "selected": false,
    "titleEn": "The Roles of Dust Growth in the Temperature Evolution and Snow Line Migration in Magnetically Accreting Protoplanetary Disks",
    "titleJa": "The Roles of Dust Growth in the Temperature Evolution and Snow Line Migration in Magnetically Accreting Protoplanetary Disks",
    "authorsEn": "Katsushi Kondo, Satoshi Okuzumi, <strong>Shoji Mori</strong>",
    "authorsJa": "Katsushi Kondo, 奥住 聡, <strong>森 昇志</strong>",
    "journalEn": "The Astrophysical Journal, 949(2):119",
    "journalJa": "The Astrophysical Journal, 949(2):119",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/acc840",
    "arxivUrl": "https://arxiv.org/abs/2205.13511",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Facc840%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2023",
    "selected": false,
    "titleEn": "Early Planet Formation in Embedded Disks (eDisk). I. Overview of the Program and First Results",
    "titleJa": "Early Planet Formation in Embedded Disks (eDisk). I. Overview of the Program and First Results",
    "authorsEn": "Nagayoshi Ohashi, John J. Tobin, Jes K. Jorgensen, ..., <strong>Shoji Mori</strong>",
    "authorsJa": "Nagayoshi Ohashi, John J. Tobin, Jes K. Jorgensen, ..., <strong>森 昇志</strong>",
    "journalEn": "The Astrophysical Journal, 951(1):8",
    "journalJa": "The Astrophysical Journal, 951(1):8",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/acd384",
    "arxivUrl": "https://arxiv.org/abs/2306.15406",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Facd384%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2023",
    "selected": false,
    "titleEn": "Early Planet Formation in Embedded Disks (eDisk). IV. The Ringed and Warped Structure of the Disk around the Class I Protostar L1489 IRS",
    "titleJa": "Early Planet Formation in Embedded Disks (eDisk). IV. The Ringed and Warped Structure of the Disk around the Class I Protostar L1489 IRS",
    "authorsEn": "Yoshihide Yamato, Yuri Aikawa, Nagayoshi Ohashi, ..., <strong>Shoji Mori</strong>, et al.",
    "authorsJa": "Yoshihide Yamato, Yuri Aikawa, Nagayoshi Ohashi, ..., <strong>森 昇志</strong>, ほか",
    "journalEn": "The Astrophysical Journal, 951(1):11",
    "journalJa": "The Astrophysical Journal, 951(1):11",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/accd71",
    "arxivUrl": "https://arxiv.org/abs/2306.15408",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Faccd71%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2023",
    "selected": false,
    "titleEn": "Early Planet Formation in Embedded Disks (eDisk). VII. Keplerian Disk, Disk Substructure, and Accretion Streamers in the Class 0 Protostar IRAS 16544-1604 in CB 68",
    "titleJa": "Early Planet Formation in Embedded Disks (eDisk). VII. Keplerian Disk, Disk Substructure, and Accretion Streamers in the Class 0 Protostar IRAS 16544-1604 in CB 68",
    "authorsEn": "Miyu Kido, Shigehisa Takakuwa, Kazuya Saigo, ..., <strong>Shoji Mori</strong>, et al.",
    "authorsJa": "Miyu Kido, Shigehisa Takakuwa, Kazuya Saigo, ..., <strong>森 昇志</strong>, ほか",
    "journalEn": "The Astrophysical Journal, 953(2):190",
    "journalJa": "The Astrophysical Journal, 953(2):190",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/acdd7a",
    "arxivUrl": "https://arxiv.org/abs/2306.15443",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Facdd7a%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2023",
    "selected": false,
    "titleEn": "Early Planet Formation in Embedded Disks (eDisk). V. Possible Annular Substructure in a Circumstellar Disk in the Ced110 IRS4 System",
    "titleJa": "Early Planet Formation in Embedded Disks (eDisk). V. Possible Annular Substructure in a Circumstellar Disk in the Ced110 IRS4 System",
    "authorsEn": "Jinshi Sai, Hsi-Wei Yen, Nagayoshi Ohashi, ..., <strong>Shoji Mori</strong>, et al.",
    "authorsJa": "Jinshi Sai, Hsi-Wei Yen, Nagayoshi Ohashi, ..., <strong>森 昇志</strong>, ほか",
    "journalEn": "The Astrophysical Journal, 954(1):67",
    "journalJa": "The Astrophysical Journal, 954(1):67",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/ace52d",
    "arxivUrl": "https://arxiv.org/abs/2307.08952",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Face52d%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2022",
    "selected": false,
    "titleEn": "Chemical and Physical Characterization of the Isolated Protostellar Source CB68: FAUST IV",
    "titleJa": "Chemical and Physical Characterization of the Isolated Protostellar Source CB68: FAUST IV",
    "authorsEn": "Muneaki Imai, Yoko Oya, Brian Svoboda, ..., <strong>Shoji Mori</strong>, et al.",
    "authorsJa": "Muneaki Imai, Yoko Oya, Brian Svoboda, ..., <strong>森 昇志</strong>, ほか",
    "journalEn": "The Astrophysical Journal, 934(1):70",
    "journalJa": "The Astrophysical Journal, 934(1):70",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/ac77e7",
    "arxivUrl": "https://arxiv.org/abs/2206.06603",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Fac77e7%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2022",
    "selected": false,
    "titleEn": "Misaligned Rotations of the Envelope, Outflow, and Disks in the Multiple Protostellar System of VLA 1623-2417: FAUST III",
    "titleJa": "Misaligned Rotations of the Envelope, Outflow, and Disks in the Multiple Protostellar System of VLA 1623-2417: FAUST III",
    "authorsEn": "Satoshi Ohashi, Claudio Codella, Nami Sakai, ..., <strong>Shoji Mori</strong>, et al.",
    "authorsJa": "Satoshi Ohashi, Claudio Codella, Nami Sakai, ..., <strong>森 昇志</strong>, ほか",
    "journalEn": "The Astrophysical Journal, 927(1):54",
    "journalJa": "The Astrophysical Journal, 927(1):54",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/ac4cae",
    "arxivUrl": "https://arxiv.org/abs/2201.07334",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Fac4cae%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2021",
    "selected": true,
    "titleEn": "Evolution of the Water Snow Line in Magnetically Accreting Protoplanetary Disks",
    "titleJa": "磁気降着原始惑星系円盤における水スノーラインの進化",
    "authorsEn": "<strong>Shoji Mori</strong>, Satoshi Okuzumi, Masanobu Kunitomo, Xue-Ning Bai",
    "authorsJa": "<strong>森 昇志</strong>, 奥住 聡, 國友 正信, Xue-Ning Bai",
    "journalEn": "The Astrophysical Journal, 916(2):72",
    "journalJa": "The Astrophysical Journal, 916(2):72",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/ac06a9",
    "arxivUrl": "https://arxiv.org/abs/2105.13101",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Fac06a9%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "This paper tracks how the water snow line, the boundary beyond which water can freeze, moves through a planet-forming disk. In disks controlled by magnetic fields, that boundary can move inside Earth's orbit within about a million years, much earlier than older models predicted, changing when and where dry rocky planets can form.",
    "abstractJa": "水が氷として存在できる境界である「水スノーライン」が、惑星形成円盤の中をどう移動するかを調べた研究です。磁場が円盤の流れを支配する場合、この境界は従来モデルよりかなり早く、およそ100万年で地球軌道の内側まで移動し得るため、乾いた岩石惑星がいつどこで作られるかの見方が変わります。"
  },
  {
    "year": "2021",
    "selected": false,
    "titleEn": "FAUST II. Discovery of a Secondary Outflow in IRAS 15398-3359: Variability in Outflow Direction during the Earliest Stage of Star Formation?",
    "titleJa": "FAUST II. Discovery of a Secondary Outflow in IRAS 15398-3359: Variability in Outflow Direction during the Earliest Stage of Star Formation?",
    "authorsEn": "Yuki Okoda, Yoko Oya, ..., <strong>Shoji Mori</strong>, et al.",
    "authorsJa": "Yuki Okoda, Yoko Oya, ..., <strong>森 昇志</strong>, ほか",
    "journalEn": "The Astrophysical Journal, 910(1):11",
    "journalJa": "The Astrophysical Journal, 910(1):11",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/abddb1",
    "arxivUrl": "https://arxiv.org/abs/2101.07404",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Fabddb1%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2021",
    "selected": true,
    "titleEn": "A New Temperature-Structure Model of Protoplanetary Disks Based on Recent Magnetohydrodynamic Studies: Snow-Line Migration and Implications for Terrestrial Planet Formation",
    "titleJa": "最新の磁気流体力学の知見に基づいた新しい原始惑星系円盤モデルの温度構造：スノーラインの移動と地球型惑星形成シナリオへの示唆",
    "authorsEn": "<strong>Shoji Mori</strong>",
    "authorsJa": "<strong>森 昇志</strong>",
    "journalEn": "Yuseijin (Journal of the Japanese Society for Planetary Sciences), 30(4):148-157 [in Japanese]",
    "journalJa": "日本惑星科学会誌『遊星人』, 30巻4号, p. 148-157",
    "url": "https://www.wakusei.jp/book/pp/2021/2021-4/2021-04-148.pdf",
    "publicationUrl": "https://www.wakusei.jp/book/pp/2021/2021-4/2021-04-148.pdf",
    "arxivUrl": null,
    "adsUrl": null,
    "abstractEn": "This review explains a newer picture of planet-forming disks in which magnetic winds, rather than strong turbulence, control how gas moves inward. In that picture the disk stays cooler than in older textbook models, the water snow line moves inward sooner, and that changes our ideas about when and where Earth-like planets formed.",
    "abstractJa": "この解説記事は、強い乱流ではなく磁気的な円盤風がガスの流れを支配するという、新しい原始惑星系円盤像を紹介するものです。この見方では円盤は従来の教科書的モデルより低温に保たれ、水スノーラインも早く内側へ移るため、地球のような惑星がいつどこでできたかの考え方が変わります。"
  },
  {
    "year": "2020",
    "selected": false,
    "titleEn": "FAUST I. The Hot Corino at the Heart of the Prototypical Class I Protostar L1551 IRS5",
    "titleJa": "FAUST I. The Hot Corino at the Heart of the Prototypical Class I Protostar L1551 IRS5",
    "authorsEn": "E. Bianchi, C. J. Chandler, C. Ceccarelli, ..., <strong>Shoji Mori</strong>, et al.",
    "authorsJa": "E. Bianchi, C. J. Chandler, C. Ceccarelli, ..., <strong>森 昇志</strong>, ほか",
    "journalEn": "Monthly Notices of the Royal Astronomical Society: Letters, 498(1):L87-L92",
    "journalJa": "Monthly Notices of the Royal Astronomical Society: Letters, 498(1):L87-L92",
    "publicationUrl": "https://doi.org/10.1093/mnrasl/slaa130",
    "arxivUrl": "https://arxiv.org/abs/2007.10275",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.1093%2Fmnrasl%2Fslaa130%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2019",
    "selected": true,
    "titleEn": "Temperature Structure in the Inner Regions of Protoplanetary Disks: Inefficient Accretion Heating Controlled by Nonideal Magnetohydrodynamics",
    "titleJa": "原始惑星系円盤内側領域の温度構造：非理想磁気流体力学に制御された非効率な降着加熱",
    "authorsEn": "<strong>Shoji Mori</strong>, Xue-Ning Bai, Satoshi Okuzumi",
    "authorsJa": "<strong>森 昇志</strong>, Xue-Ning Bai, 奥住 聡",
    "journalEn": "The Astrophysical Journal, 872(1):98",
    "journalJa": "The Astrophysical Journal, 872(1):98",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/ab0022",
    "arxivUrl": "https://arxiv.org/abs/1901.06921",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Fab0022%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "This paper asks whether inward-moving gas really heats the inner disk enough to reshape planet formation. The simulations show that most of the heating happens high above the disk's dense middle layer, where heat escapes easily, so that middle layer often stays cooler and is set mainly by starlight.",
    "abstractJa": "円盤の内側で、流れ込むガスが本当に十分な熱を生んで惑星形成に大きく効くのかを調べた研究です。シミュレーションの結果、加熱の多くは円盤の密な中心部ではなく上の薄い層で起こり、熱が逃げやすいため、中心部の温度は思ったほど上がらず、主に星の光で決まることが分かりました。"
  },
  {
    "year": "2019",
    "selected": false,
    "titleEn": "The Generalized Nonlinear Ohm's Law: How a Strong Electric Field Influences Nonideal MHD Effects in Dusty Protoplanetary Disks",
    "titleJa": "The Generalized Nonlinear Ohm's Law: How a Strong Electric Field Influences Nonideal MHD Effects in Dusty Protoplanetary Disks",
    "authorsEn": "Satoshi Okuzumi, <strong>Shoji Mori</strong>, Shu-ichiro Inutsuka",
    "authorsJa": "奥住 聡, <strong>森 昇志</strong>, 犬塚 修一郎",
    "journalEn": "The Astrophysical Journal, 878(2):133",
    "journalJa": "The Astrophysical Journal, 878(2):133",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/ab2046",
    "arxivUrl": "https://arxiv.org/abs/1905.03153",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Fab2046%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "",
    "abstractJa": ""
  },
  {
    "year": "2017",
    "selected": false,
    "titleEn": "Electron Heating and Saturation of Self-regulating Magnetorotational Instability in Protoplanetary Disks",
    "titleJa": "Electron Heating and Saturation of Self-regulating Magnetorotational Instability in Protoplanetary Disks",
    "authorsEn": "<strong>Shoji Mori</strong>, Takayuki Muranushi, Satoshi Okuzumi, Shu-ichiro Inutsuka",
    "authorsJa": "<strong>森 昇志</strong>, 村主 崇行, 奥住 聡, 犬塚 修一郎",
    "journalEn": "The Astrophysical Journal, 849(2):86",
    "journalJa": "The Astrophysical Journal, 849(2):86",
    "publicationUrl": "https://doi.org/10.3847/1538-4357/aa8e42",
    "arxivUrl": "https://arxiv.org/abs/1709.07026",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F1538-4357%2Faa8e42%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "This study numerically investigates how electron heating modifies the nonlinear evolution of magnetorotational instability in weakly ionized disks. It shows that when electron heating starts at low current density, magnetic turbulence is strongly suppressed and a laminar accretion flow supported by ordered magnetic fields can emerge.",
    "abstractJa": "この研究は、電子加熱が低電離円盤における磁気回転不安定性の非線形成長をどのように変えるかを数値的に調べたものです。比較的低い電流密度で電子加熱が始まると磁気乱流は大きく抑制され、秩序だった磁場に支えられた層流的な降着流が現れ得ることを示しています。"
  },
  {
    "year": "2016",
    "selected": false,
    "titleEn": "Electron Heating in the Magnetorotational Instability: Implications for Turbulence Strength in Outer Regions of Protoplanetary Disks",
    "titleJa": "Electron Heating in the Magnetorotational Instability: Implications for Turbulence Strength in Outer Regions of Protoplanetary Disks",
    "authorsEn": "<strong>Shoji Mori</strong>, Satoshi Okuzumi",
    "authorsJa": "<strong>森 昇志</strong>, 奥住 聡",
    "journalEn": "The Astrophysical Journal, 817(1):52",
    "journalJa": "The Astrophysical Journal, 817(1):52",
    "publicationUrl": "https://doi.org/10.3847/0004-637X/817/1/52",
    "arxivUrl": "https://arxiv.org/abs/1505.04896",
    "adsUrl": "https://ui.adsabs.harvard.edu/search/q=doi:%2210.3847%2F0004-637x%2F817%2F1%2F52%22/sort=date%20desc%2C%20bibcode%20desc",
    "abstractEn": "This paper examines how electron heating feeds back on MRI-driven turbulence in the outer disk. It predicts that the region where electron heating limits MRI saturation can extend much farther outward than the conventional dead zone, implying substantially weaker turbulence and more difficult dust growth in those regions.",
    "abstractJa": "この論文は、電子加熱が外側円盤の MRI 乱流へどのようにフィードバックするかを調べたものです。電子加熱が MRI の飽和を制限する領域は従来のデッドゾーンよりはるか外側まで広がり得るため、その領域では乱流強度が大きく弱まり、ダスト成長も起こりにくくなる可能性を示しています。"
  }
];
